### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'Verdant' was not present in the dictionary.

### ISSUE THREAD

**Issue by ghost** [GabeHasWon/VerdantMod#1]
Error on Ubuntu Server when trying to create a world
[server.log](https://cdn.lucaservers.com/tmod/00001-server.log) file for complete info

Here is the stack
```[20:43:08.565] [Main Thread/INFO] [StatusText]: 63.8% - Smoothing the world - 66.
[20:43:08.623] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: The given key 'Verdant' was not present in the dictionary.
   at Verdant.Tiles.Verdant.Basic.Blocks.VerdantLeaves.KillTile(Int32 i, Int32 j, Boolean& fail, Boolean& effectOnly, Boolean& noItem) in VerdantLeaves.cs:line 22
   at Terraria.ModLoader.TileLoader.KillTile(Int32 i, Int32 j, Int32 type, Boolean& fail, Boolean& effectOnly, Boolean& noItem) in tModLoader\Terraria\ModLoader\TileLoader.cs:line 501
   at Terraria.WorldGen.KillTile(Int32 i, Int32 j, Boolean fail, Boolean effectOnly, Boolean noItem) in tModLoader\Terraria\WorldGen.cs:line 40940
   at Terraria.WorldGen.<>c.<GenerateWorld>b__362_55(GenerationProgress progress, GameConfiguration passConfig) in tModLoader\Terraria\WorldGen.cs:line 8838
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12385
   at DMD<Terraria.WorldGen::do_worldGenCallBack>(Object threadContext)
   at Terraria.WorldGen.worldGenCallback(Object threadContext)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[20:43:08.627] [.NET ThreadPool Worker/ERROR] [tML]: A problem was encountered during world generation
Smooth World
System.Collections.Generic.KeyNotFoundException: The given key 'Verdant' was not present in the dictionary.
   at Verdant.Tiles.Verdant.Basic.Blocks.VerdantLeaves.KillTile(Int32 i, Int32 j, Boolean& fail, Boolean& effectOnly, Boolean& noItem) in VerdantLeaves.cs:line 22
   at Terraria.ModLoader.TileLoader.KillTile(Int32 i, Int32 j, Int32 type, Boolean& fail, Boolean& effectOnly, Boolean& noItem) in tModLoader\Terraria\ModLoader\TileLoader.cs:line 501
   at Terraria.WorldGen.KillTile(Int32 i, Int32 j, Boolean fail, Boolean effectOnly, Boolean noItem) in tModLoader\Terraria\WorldGen.cs:line 40940
   at Terraria.WorldGen.<>c.<GenerateWorld>b__362_55(GenerationProgress progress, GameConfiguration passConfig) in tModLoader\Terraria\WorldGen.cs:line 8838
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
[20:43:08.633] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(MethodDebugInformationHandle handle)
   at System.Reflection.Metadata.MethodDebugInformation.get_SequencePointsBlob()
   at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(Assembly assembly, String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, Boolean isFileLayout, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
   at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 skipFrames, Boolean fNeedFileInfo, Exception e)
   at Hook<System.Diagnostics.StackTrace::.ctor>?7658356(StackTrace , Exception , Boolean )
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at log4net.ObjectRenderer.DefaultRenderer.RenderObject(RendererMap rendererMap, Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj)
   at log4net.Core.LoggingEvent.GetExceptionString()
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(TextWriter writer, LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(LoggingEvent loggingEvent)
   at log4net.Appender.DebugAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
   at log4net.Util.AppenderAttachedImpl.AppendLoopOnAppenders(LoggingEvent loggingEvent)
   at log4net.Repository.Hierarchy.Logger.CallAppenders(LoggingEvent loggingEvent)
   at log4net.Repository.Hierarchy.Logger.Log(Type callerStackBoundaryDeclaringType, Level level, Object message, Exception exception)
   at log4net.Core.LogImpl.Error(Object message, Exception exception)
   at Terraria.WorldGen.worldGenCallback(Object threadContext)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[20:43:08.629] [.NET ThreadPool Worker/ERROR] [Terraria]: A problem was encountered during world generation
System.Collections.Generic.KeyNotFoundException: The given key 'Verdant' was not present in the dictionary.
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 60
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12385
   at DMD<Terraria.WorldGen::do_worldGenCallBack>(Object threadContext)
   at Terraria.WorldGen.worldGenCallback(Object threadContext)
```

**Comment by GabeHasWon** [comment]
Thanks for the report! Working on a major crash error currently, will get to it after that's taken care of.

**Comment by GabeHasWon** [comment]
The new update should hopefully have the fix, lemme know if it worked!

**Comment by ghost** [comment]
I can cofirm it is fixed
